Remove allocations related to views
JuliaSmoothOptimizers/NLPModelsJuMP.jl pull request #124
Opened 2022-08-03 20:27 UTC by amontoison

2022-08-03 22:06 UTC, tmigot requested changes
This looks a great improvement! I just have cosmetic comments.

2022-08-03 22:06 UTC, tmigot commented on src/moi_nls_model.jl
> +    view(Fx, nls.nls_meta.lin) .+= nls.linequ.constants
Would it be cleaner to use `view` like this everywhere instead of loops?

2022-08-05 03:55 UTC, amontoison commented on src/moi_nls_model.jl
> +    view(Fx, nls.nls_meta.lin) .+= nls.linequ.constants
Yes, good idea!
I also added a function `coo_sym_add_mul!`.

2022-08-05 13:34 UTC, tmigot requested changes
Thanks @amontoison ! That's just minor comments.

2022-08-05 13:34 UTC, tmigot commented on src/moi_nls_model.jl
> +    view(rows, 1:nls.lls.nnzh) .= nls.lls.hessian.rows
Is there no coverage here because we have no NLS with linear constraints?

2022-08-05 13:34 UTC, tmigot commented on src/utils.jl
> +function coo_sym_add_mul!(
This function looks a bit like the function `coo_sym_mul!` in `SparseMatricesCOO.jl` https://github.com/JuliaSmoothOptimizers/SparseMatricesCOO.jl/blob/6bfc6ca2cdcc6fd746aebb535425754993578dcc/src/coo_linalg.jl#L66 #109

2022-08-05 13:34 UTC, tmigot commented on src/utils.jl
> +function coo_sym_add_mul!(
If that's the same function, we could reuse your docstring :)

2022-08-05 13:34 UTC, tmigot commented on src/moi_nls_model.jl
> +      row, col = hesslag_struct[shift_index]
Can you check if this allocates? Sometimes, it does when we create a tuple.

2022-08-05 13:35 UTC, tmigot commented on src/moi_nls_model.jl
> +    view(rows, 1:nls.lls.nnzh) .= nls.lls.hessian.rows
We can handle this in a separate issue.

2022-08-05 20:09 UTC, tmigot approved these changes
Thanks

2022-08-05 20:21 UTC, merged