Add support for expressions of type VariableRef
JuliaSmoothOptimizers/NLPModelsJuMP.jl pull request #136
Opened 2022-08-27 02:19 UTC by amontoison

2022-08-29 11:55 UTC, tmigot requested changes
Thanks for the changes. I think it lacks an example.

2022-08-29 11:55 UTC, tmigot commented on src/utils.jl
> +      if isa(expr, VF)
Can you add an example/unit test for this?

2022-08-29 11:55 UTC, tmigot commented on src/utils.jl
> +      if isa(expr, VF)
Same here

2022-08-29 11:55 UTC, tmigot commented on src/utils.jl
> +# Expressions
I don't know how useful that is, but why not.

2022-08-29 12:41 UTC, amontoison commented on src/utils.jl
> +      if isa(expr, VF)
We already have example/unit test for this: https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/main/test/nls_problems/hs30.jl#L6
I don't understand why the tests passed before.

2022-08-29 12:43 UTC, amontoison commented on src/utils.jl
> +      if isa(expr, VF)
We also need a NLPModel to verify the results ?

2022-08-29 12:43 UTC, amontoison commented on src/utils.jl
> +# Expressions
It helps me to remember the type of the objects used in MOI.

2022-08-29 12:44 UTC, tmigot commented on src/utils.jl
> +      if isa(expr, VF)
But according to `codecov` the tests are still not passing here

2022-08-31 18:11 UTC, tmigot approved these changes
LGTM, thanks!

2022-08-31 18:14 UTC, merged

2022-08-31 18:16 UTC, amontoison commented
We can do a new release now.
@tmigot `v12.0` or `v11.2`?

2022-08-31 18:28 UTC, tmigot commented
v12.0 because we drop JuMP 1.0 and 1.1

2022-08-31 18:29 UTC, tmigot commented
Thanks!