Add MOI wrapper
JuliaSmoothOptimizers/NLPModelsJuMP.jl pull request #157
Opened 2023-07-17 14:15 UTC by blegat

2023-07-24 14:31 UTC, tmigot requested changes
Thanks @blegat for the PR! That's a great update. I made a couple of comments/questions, but nothing big I think.

2023-07-24 14:31 UTC, tmigot commented on Project.toml
> +NLPModelsTest = "7998695d-6960-4d3a-85c4-e1bceb8cd856"
Do we need to add this in the deps?
```suggestion
```

2023-07-24 14:31 UTC, tmigot commented on src/MOI_wrapper.jl
> +end
Wouldn't it be more efficient to have a non-mutable struct defined for a given problem? At leat for the stats, doing `reset!(stats)` re-initializes all the fields.

2023-07-24 14:31 UTC, tmigot commented on src/MOI_wrapper.jl
> +MOI.get(::Optimizer, ::MOI.SolverName) = "NLPModels"
Could we access `MOI.RawOptimizerAttribute("solver")` to make a more precise name?

2023-07-24 14:31 UTC, tmigot commented on src/MOI_wrapper.jl
> +        # TODO
What needs to be done here?

2023-07-24 23:46 UTC, blegat commented on src/MOI_wrapper.jl
> +    # TODO
Similar to `PrimalStatus` but for the dual variables. So if there is no dual available, just return `NO_SOLUTION`. If you have one and you know it's feasible, return `FEASIBLE_POINT`, ...

2023-07-24 23:48 UTC, blegat commented on src/MOI_wrapper.jl
> +        # TODO
You have a better understanding of what's the status of the primal given the `optimizer.stats`, ...
See here fore the list

2023-07-25 00:11 UTC, blegat commented on src/MOI_wrapper.jl
> +end
But then how do we update it with what is returned by `solve!`. Isn't that small overhead negligible as it's not in the hot loop ?

2023-07-25 10:57 UTC, blegat commented on src/MOI_wrapper.jl
> +MOI.get(::Optimizer, ::MOI.SolverName) = "NLPModels"
Yes, is there a way to get this in the NLPModels API ?

2023-07-26 12:45 UTC, tmigot reviewed
Thanks again @blegat , I just made a couple more comments but we should be very close now.

2023-07-26 12:45 UTC, tmigot commented on src/MOI_wrapper.jl
> +    model.stats = SolverCore.solve!(model.solver, model.nlp; options...)
About updating stats in a hot loop, you should use this:
```suggestion
    SolverCore.solve!(model.solver, model.nlp, model.stats; options...)
```

2023-07-26 12:45 UTC, tmigot commented on src/MOI_wrapper.jl
> +end
I made a comment on your solve! call for this

2023-07-26 12:45 UTC, tmigot commented on src/MOI_wrapper.jl
> +MOI.get(::Optimizer, ::MOI.SolverName) = "NLPModels"
Do you mean to access the solver name ? We don't really have that now unfortunately, but it is a good suggestion. Something like
```
get_solver_name(solver)
```
would do the trick.

2023-07-26 12:45 UTC, tmigot commented on src/MOI_wrapper.jl
> +MOI.get(::Optimizer, ::MOI.SolverName) = "NLPModels"
I opened an issue for this https://github.com/JuliaSmoothOptimizers/SolverCore.jl/issues/73

2023-07-26 12:45 UTC, tmigot commented on src/MOI_wrapper.jl
> +        # TODO
Well, there is no really other status than `:first_order` that ensures that you have a ''feasible'' point. That might also be interesting information to add.
You can have access to `stats.primal_feas` which is the norm if primal feasibility if that helps.

If nothing can be added let's keep it for later.

2023-07-26 12:45 UTC, tmigot commented on src/MOI_wrapper.jl
> +    # TODO
Same as above. Just a complementary question, what do you mean by dual feasibility when you have bounds and inequalities ? I am asking as there could be more than one answer hère I think.

2023-07-27 13:10 UTC, tmigot commented on src/MOI_wrapper.jl
>      end
```suggestion
    else
      options[:verbose] = 1
    end
```

2023-07-27 13:25 UTC, tmigot commented on src/MOI_wrapper.jl
> +    # TODO how to I reset `stats` ?
There is a SolverCore.reset! function for that : 
```suggestion
    reset!(stats)
```

2023-07-27 13:28 UTC, tmigot commented on src/MOI_wrapper.jl
> +    # TODO how to I reset `stats` ?
https://github.com/JuliaSmoothOptimizers/SolverCore.jl/blob/e310d911ea8de145979584c9af8ada2d02e77c90/src/stats.jl#L178

2023-07-28 12:56 UTC, tmigot commented on src/MOI_wrapper.jl
> +    # TODO how to I reset `stats` ?
Ahaha! So true

2023-07-28 12:59 UTC, tmigot approved these changes
Thanks @blegat for initiating this new feature. The PR looks good to me now.

2023-07-28 13:04 UTC, merged