Support quadratic constraints
JuliaSmoothOptimizers/NLPModelsJuMP.jl pull request #181
Opened 2024-06-20 04:09 UTC by amontoison

close #50 
@tmigot You should be happy now :smiley:

2024-06-20 05:48 UTC, amontoison commented
@tmigot We should probably add HS61, HS100 and HS219 in `NLPModelsTest.jl` for more robust tests.

2024-06-21 03:05 UTC, amontoison commented
If we replace `@NLconstraint` with `@constraint` for the quadratic constraints in `hs6`, `hs10`, `hs11`, and `hs14`, almost all tests pass.
The failing tests are related to this issue: [JuliaSmoothOptimizers/NLPModelsTest.jl#109](https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/issues/109).

2024-06-21 13:46 UTC, tmigot requested changes
Hi @amontoison ! Thanks for the PR that's great.
I just had minor comments to add some tests.
How did you verify the result?

2024-06-21 15:11 UTC, amontoison commented on src/utils.jl
>        end
Yes, I did a typo here a long time ago but by chance JuMP seems to only stored the upper triangular part of the symmetric matrix. We never went in the "else" block.

2024-06-21 15:13 UTC, amontoison commented on src/utils.jl
> +  return nlin, lincon, lin_lcon, lin_ucon, quadcon, quad_lcon, quad_ucon
We can't store `nquad` in the `NLPMeta` structure like `nlin` so I stored it in `quadcon`.

2024-06-21 16:46 UTC, amontoison commented on test/nlp_problems/hs100.jl
> +  @constraint(nlp, -4 * x[1]^2 - x[2]^2 + 3 * x[1] * x[2] - 2 * x[3]^2 - 5 * x[6] + 11 * x[7] ≥ 0)
I replaced
```julia
@constraint(nlp, 196 - 23 * x[1] - x[2]^2 - 6 * x[6]^2 + 8 * x[7] ≥ 0)
```
by
```julia
@constraint(nlp, -196 + 23 * x[1] + x[2]^2 + 6 * x[6]^2 - 8 * x[7] ≤ 0)
```

2024-06-21 18:38 UTC, tmigot approved these changes
Thanks @amontoison ! It looks good to me.
I think we just need a problem in NLPModelsTest that has both quadratic and nonlinear constraints.
Let's go for 0.13.0 when you are ready.

2024-06-21 19:14 UTC, amontoison commented on src/utils.jl
> +function parser_VQF(fun, set, nvar, qcons, quad_lcon, quad_ucon, index_map)
Done!

2024-06-21 20:37 UTC, merged