Add jth_hess_coord!, jth_hprod! and ghjvprod!
JuliaSmoothOptimizers/NLPModelsJuMP.jl pull request #193
Opened 2024-08-18 06:18 UTC by amontoison

@tmigot Do we have some unit tests for these routines?

2024-08-19 11:47 UTC, tmigot commented
> @tmigot Do we have some unit tests for these routines?

You need to add `exclude = []` here https://github.com/amontoison/NLPModelsJuMP.jl/blob/10ccc77db66baad1f357f71fe22f57eea10b8350/test/nlp_consistency.jl#L7

The unit tests are https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/blob/main/src/nlp/consistency.jl but excluded by default for these.

2024-08-19 11:47 UTC, tmigot requested changes
Thanks @amontoison ! just some comments

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +  # Don't we have a counter :neval_ghjvprod?
```suggestion
  increment!(nlp, :neval_hprod)
```

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +  vals .= 0.0
```suggestion
  increment!(nlp, :neval_jhess)
  @rangecheck 1 nlp.meta.ncon j
  vals .= 0.0
```

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +  hv .= 0.0
```suggestion
  increment!(nlp, :neval_jhprod)
  @rangecheck 1 nlp.meta.ncon j
  hv .= 0.0
```

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +  if nlp.meta.nlin + nlp.quadcon.nquad + 1 ≤ j ≤ nlp.meta.ncon
```suggestion
  else
```

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +  if nlp.meta.nlin + nlp.quadcon.nquad + 1 ≤ j ≤ nlp.meta.ncon
```suggestion
  else
```

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 1.0
How do we know this vector is zeros?

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 0.0
If we do these things, maybe add a `reset!` function?

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 1.0
see above

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 0.0
see above

2024-08-19 11:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    hv = zeros(Float64, nlp.meta.nvar)
Please make an issue for that

2024-08-19 12:42 UTC, amontoison commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 1.0
I commited your suggestion but it's wrong. We have a issue is `j` is an index of linear constraint of if `j` is not an index of a valid constraint.

2024-08-19 17:55 UTC, amontoison commented on src/moi_nlp_model.jl
> +      λ,
```suggestion
      nlp.λ,
```

2024-08-19 18:38 UTC, amontoison commented
@tmigot I don't understand the CI error.
It seems related to the counter for `neval_jhprod`.

2024-08-19 18:39 UTC, amontoison commented on src/moi_nlp_model.jl
> +    hv = zeros(Float64, nlp.meta.nvar)
I added `hv` in the structure of `MathOptNLPModel`.

2024-08-19 21:47 UTC, tmigot requested changes

2024-08-19 21:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    jth_hprod!(nlp, x, v, i, nlp.hv)
This is your extra evaluations
```suggestion
    jth_hprod!(nlp, x, v, i, nlp.hv)
    decrement!(nlp, :neval_jhprod)
```

2024-08-19 21:47 UTC, tmigot commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 1.0
Argh, sorry. Should've been a elseif then?

2024-08-19 22:23 UTC, tmigot commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 0.0
Yeah... not necessary. Your choice :).

2024-08-21 22:36 UTC, amontoison commented on src/moi_nlp_model.jl
> +    nlp.λ[j - nlp.meta.nlin - nlp.quadcon.nquad] = 1.0
Yes, I added a commit with two `elseif`.

2024-09-01 09:30 UTC, tmigot commented on src/moi_nlp_model.jl
> +    jth_hprod!(nlp, x, v, i, nlp.hv)
This is still the line you need to add for the counters

2024-09-01 16:11 UTC, tmigot approved these changes
Thanks @amontoison !

2024-09-01 16:45 UTC, merged